[package]
name = "bl602-hello-world"
version = "0.1.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv-rt = "*"
bl602-hal = { path = "../../../bl602-hal" }
